### ISSUE TITLE
Grammar doesn't handle multiline preprocessor declarations

### ISSUE THREAD

**Issue by genotrance** [tree-sitter/tree-sitter-c#11] opened 2018-11-16 20:39 UTC
Tried to parse tree-sitter's [parser.h](https://github.com/tree-sitter/tree-sitter/blob/master/include/tree_sitter/parser.h#L107) and you get errors since the `\` is misinterpreted as a preprocessor argument.

Output:

```
     comment /*
 *  Lexer Macros
 */
     preproc_function_def
      identifier START_LEXER
      preproc_params ()
      preproc_arg            \           <====
     declaration
      primitive_type bool
      init_declarator
       identifier result
       false false
     ERROR                               <====
      ERROR \
     declaration
      primitive_type int32_t
      identifier lookahead
     ERROR
      ERROR \
     labeled_statement
      statement_identifier next_state
      ERROR
       ERROR \
      expression_statement
       assignment_expression
        identifier lookahead
        field_expression
         identifier lexer
         field_identifier lookahead
```

**Comment by maxbrunsfeld** [comment] 2018-11-16 20:48
Hmm, I can't reproduce that problem; I'm not seeing any problems parsing those types of `#define` directives.

I *do* get two errors when parsing `parser.h`, but it's only because of this construct:

```c
#ifdef __cplusplus
extern "C" {
#endif

// ...

#ifdef __cplusplus
}
#endif
```

That's a common C header idiom that the grammar doesn't explicitly handle (we just rely on error recovery for dealing with it, which works ok).

If I delete those `#ifdef __cplusplus` blocks, the file parsers with no errors.

**Comment by maxbrunsfeld** [comment] 2018-11-16 20:49
How are you parsing the file and getting that output? Can you report the output of running `node_modules/.bin/tree-sitter parser src/tree_sitter/parser.h` from the `tree-sitter-c` directory?

**Comment by genotrance** [comment] 2018-11-16 21:13
I'm the author of [nimtreesitter](https://github.com/genotrance/nimtreesitter). I am working on a way to wrap C/C++ using tree-sitter and pulling it into [Nim](https://nim-lang.org).

I have a simple tool that uses tree-sitter to generate the ast output in plain text.

If you tell me how to run tree-sitter-c locally, I can build/test and give you the output that way.

**Comment by Ben3eeE** [comment] 2018-11-16 21:38
@genotrance Make sure you are running the latest version of tree-sitter-c. A lot of macro related errors have been fixed in the last couple of releases.

To run `tree-sitter-c` locally to test this I would suggest checking out the documentation: http://tree-sitter.github.io/tree-sitter/creating-parsers#installing-the-tools and http://tree-sitter.github.io/tree-sitter/creating-parsers#writing-unit-tests

If you have specific questions or get stuck on something while following these steps please let us know and we are happy to help.

**Comment by maxbrunsfeld** [comment] 2018-11-16 21:58
> I'm the author of nimtreesitter.

That's really cool, nice work!

> If you tell me how to run tree-sitter-c locally, I can build/test and give you the output that way.

> If you tell me how to run tree-sitter-c locally,

Like I mentioned above, the easiest way to test the parsers at the command line is with the Tree-sitter CLI.

If you install `node`, you can do this:

```
cd tree-sitter-c
npm install
node_modules/.bin/tree-sitter  parse  src/tree_sitter/parser.h
```

**Comment by maxbrunsfeld** [comment] 2018-11-16 22:00
Oh, I think I just found the problem. When using CRLF line endings, the `\` line continuation isn't handled correctly. Thanks for the report!

**Comment by maxbrunsfeld** [comment] 2018-11-16 22:04
Fixed.

**Closed** 2018-11-16 22:04 UTC

**Comment by genotrance** [comment] 2018-11-20 22:53
Looks like this needs to be fixed in tree-sitter-cpp as well since it is still broken there.

**Comment by maxbrunsfeld** [comment] 2018-11-20 22:57
Are you seeing this with the latest version of `tree-sitter-cpp`, 0.13.11?

I believe it was fixed there in https://github.com/tree-sitter/tree-sitter-cpp/commit/f3a6ad103946871a518dc7baf9fbd5b61cae219b. Are you still seeing problems?

**Comment by genotrance** [comment] 2018-11-20 23:43
Never mind - my mistake - looks like I had an old build for cpp still. Apologies.
